# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
template: !include template-sensors.yaml

homeassistant:
  media_dirs:
    snapshots: /config/www/images/
  allowlist_external_dirs:
    - /config/www/images

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

logger:
  default: info

lovelace:
  mode: storage
  dashboards:
    tent-view:
      mode: yaml
      title: Tent
      icon: mdi:sprout-outline
      show_in_sidebar: true
      filename: Tent.yaml

shell_command:
  pushupdates_to_github: /bin/bash pushupdates.sh

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/community/lovelace-card-mod/card-mod.js

timer:
  dosetimer:
    duration: "{{ 00:00 states('input_number.peristaltic_pump_flow_rate') | float / 60 * 5 }}
