- platform: template
  sensors:
    vapor_deficit:
      friendly_name: "vpd in kpa"
      unique_id: vapor_pressure_deficit
      icon_template: mdi:water-opacity
      value_template: >-
        {% set T = ((states('sensor.tent_temperature') | float) - 32) * 5/9 %}
        {% set RH = states('sensor.tent_humidity')|float %}
        {% set SVP = 0.61078 * e ** (17.2694 * T / (T + 238.3)) %}
        {% set VPD = ((100-RH) / 100) * SVP %}
        {{-VPD | round(2) -}}
      unit_of_measurement: "kPa"
    shellypro4pm_84cca87fa4f4_current_1:
      friendly_name: Nutrient Pump Current
      unique_id: shellypro4pm_84cca87fa4f4_current_1
      icon_template: mdi:current-ac
      unit_of_measurement: "A"
      value_template: "{{ (states('sensor.shellypro4pm_84cca87fa4f4_power_1') | float / states('sensor.shellypro4pm_84cca87fa4f4_voltage_1') | float ) | round(2)  }}"
    shellypro4pm_84cca87fa4f4_current_2:
      friendly_name: Air Pump Current
      unique_id: shellypro4pm_84cca87fa4f4_current_2
      icon_template: mdi:current-ac
      unit_of_measurement: "A"
      value_template: "{{ (states('sensor.shellypro4pm_84cca87fa4f4_power_2') | float / states('sensor.shellypro4pm_84cca87fa4f4_voltage_1') | float) | round(2)  }}"
    shellypro4pm_84cca87fa4f4_current_3:
      friendly_name: Dehumidifier
      unique_id: shellypro4pm_84cca87fa4f4_current_3
      icon_template: mdi:current-ac
      unit_of_measurement: "A"
      value_template: "{{ (states('sensor.shellypro4pm_84cca87fa4f4_power_3') | float / states('sensor.shellypro4pm_84cca87fa4f4_voltage_3') | float ) | round(2)  }}"
    shellypro4pm_84cca87fa4f4_current_4:
      friendly_name: Humidifier Current
      unique_id: shellypro4pm_84cca87fa4f4_current_4
      icon_template: mdi:current-ac
      unit_of_measurement: "A"
      value_template: "{{ (states('sensor.shellypro4pm_84cca87fa4f4_power_4') | float / states('sensor.shellypro4pm_84cca87fa4f4_voltage_4') | float ) | round(2)  }}"
    shellypro4pm_84cca87f1ae0_current_1:
      friendly_name: Grow Light Current
      unique_id: shellypro4pm_884cca87f1ae0_switch01_current_1
      icon_template: mdi:current-ac
      unit_of_measurement: "A"
      value_template: "{{ (states('sensor.shellypro4pm_84cca87f1ae0_power_1') | float / states('sensor.shellypro4pm_84cca87f1ae0_voltage_1') | float ) | round(2)  }}"
    shellypro4pm_84cca87f1ae0_current_2:
      friendly_name: Tent Exhaust Current
      unique_id: shellypro4pm_84cca87f1ae0_current_2
      icon_template: mdi:current-ac
      unit_of_measurement: "A"
      value_template: "{{ (states('sensor.shellypro4pm_84cca87f1ae0_power_2') | float / states('sensor.shellypro4pm_84cca87f1ae0_voltage_2') | float ) | round(2)  }}"
    shellypro4pm_84cca87f1ae0_current_3:
      friendly_name: Bottom Circulation Fan Current
      unique_id: shellypro4pm_84cca87f1ae0_current_3
      icon_template: mdi:current-ac
      unit_of_measurement: "A"
      value_template: "{{ (states('sensor.shellypro4pm_84cca87f1ae0_power_3') | float / states('sensor.shellypro4pm_84cca87f1ae0_voltage_3') | float ) | round(2)  }}"
    shellypro4pm_84cca87f1ae0_current_4:
      friendly_name: Top Circulation Fan Current
      unique_id: shellypro4pm_84cca87f1ae0_current_4
      icon_template: mdi:current-ac
      unit_of_measurement: "A"
      value_template: "{{ (states('sensor.shellypro4pm_84cca87f1ae0_power_4') | float / states('sensor.shellypro4pm_84cca87f1ae0_voltage_4') | float ) | round(2)  }}"
    shellyem_e45229_current:
      friendly_name: Total Current
      unique_id: shellyem_e45229_channel_1_current
      icon_template: mdi:current-ac
      unit_of_measurement: "A"
      value_template: "{{ (states('sensor.shellyem_e45229_channel_1_power') | float / states('sensor.shellyem_e45229_channel_1_voltage') | float ) | round(2)  }}"
    weeks_since_sprout:
      friendly_name: Weeks Since Sprout
      unique_id: weeks_since_sprout
      unit_of_measurement: "Weeks"
      value_template: "{{ (states('sensor.anniversary_days_since_sprout') | float / 7 ) | round(0, 'floor')  }}"
    weeks_since_flower:
      friendly_name: Weeks Since Flower
      unique_id: weeks_since_flower
      unit_of_measurement: "Weeks"
      value_template: "{{ (states('sensor.anniversary_flipped_to_flower') | float / 7 ) | round(0, 'floor')  }}"
    weeks_remaining:
      friendly_name: Weeks Remaining
      unique_id: weeks_remaining
      unit_of_measurement: "Weeks"
      value_template: "{{ 12 - (states('sensor.weeks_since_flower')| float ) | round(0, 'floor')  }}"
    ph_setmax:
      friendly_name: "pH Threshold Max"
      unique_id: ph_setmax
      value_template: "{{ states('input_number.ph_target') | float + states('input_number.ph_tolerance') | float }}"
    ph_setmin:
      friendly_name: "pH Threshold Min"
      unique_id: ph_setmin
      value_template: "{{ states('input_number.ph_target') | float - states('input_number.ph_tolerance') | float }}"
    tenttemp_setmax:
      friendly_name: "Air Temp Threshold Max"
      unique_id: tenttemp_setmax
      value_template: "{{ states('input_number.air_temperature_target') | float + states('input_number.air_temperature_tolerance') | float }}"
    tenttemp_setmin:
      friendly_name: "Air Temp Threshold Min"
      unique_id: tenttemp_setmin
      value_template: "{{ states('input_number.air_temperature_target') | float - states('input_number.air_temperature_tolerance') | float }}"
    tenthum_setmax:
      friendly_name: "Humidity Threshold Max"
      unique_id: tenthum_setmax
      value_template: "{{ states('input_number.humidity_target') | float + states('input_number.humidity_tolerance') | float }}"
    tenthum_setmin:
      friendly_name: "Humidity Threshold Min"
      unique_id: tenthum_setmin
      value_template: "{{ states('input_number.humidity_target') | float - states('input_number.humidity_tolerance') | float }}"
    watertemp_setmax:
      friendly_name: "Water Temp Threshold Max"
      unique_id: watertemp_setmax
      value_template: "{{ states('input_number.water_temperature_target') | float + states('input_number.water_temperature_tolerance') | float }}"
    watertemp_setmin:
      friendly_name: "Water Temp Threshold Min"
      unique_id: watertemp_setmin
      value_template: "{{ states('input_number.water_temperature_target') | float - states('input_number.water_temperature_tolerance') | float }}"
    duel_fuel_1_full_dose:
      friendly_name: "Duel Fuel 1 Full Dose"
      unique_id: duel_fuel_1_full_dose
      value_template: "{{ states('input_number.duel_fuel_1')|float * states('input_number.reservoir_volume')|float}}"
      unit_of_measurement: "ml"
    duel_fuel_2_full_dose:
      friendly_name: "Duel Fuel 2 Full Dose"
      unique_id: duel_fuel_2_full_dose
      value_template: "{{ states('input_number.duel_fuel_2')|float * states('input_number.reservoir_volume')|float}}"
      unit_of_measurement: "ml"
    vitathrive_full_dose:
      friendly_name: "Vitathrive Full Dose"
      unique_id: vitathrive_full_dose
      value_template: "{{ states('input_number.vitathrive')|float * states('input_number.reservoir_volume')|float}}"
      unit_of_measurement: "ml"
    rezin_full_dose:
      friendly_name: "Rezin Full Dose"
      unique_id: rezin_full_dose
      value_template: "{{ states('input_number.rezin')|float * states('input_number.reservoir_volume')|float}}"
      unit_of_measurement: "ml"
    massive_bloom_full_dose:
      friendly_name: "Massive Bloom Full Dose"
      unique_id: massive_bloom_full_dose
      value_template: "{{ states('input_number.massive_bloom')|float * states('input_number.reservoir_volume')|float}}"
      unit_of_measurement: "ml"
    liquid_weight_full_dose:
      friendly_name: "Liquid Weight Full Dose"
      unique_id: liquid_weight_full_dose
      value_template: "{{ states('input_number.liquid_weight')|float * states('input_number.reservoir_volume')|float}}"
      unit_of_measurement: "ml"
    duel_fuel_1_dose_length:
      friendly_name: "Duel Fuel 1 Dose Length"
      unique_id: duel_fuel_1_dose_length
      value_template: "{{ states('sensor.duel_fuel_1_full_dose')|float / (states('input_number.peristaltic_pump_flow_rate')|float / 60 ) }}"
      unit_of_measurement: "seconds"
    duel_fuel_2_dose_length:
      friendly_name: "Duel Fuel 2 Dose Length"
      unique_id: duel_fuel_2_dose_length
      value_template: "{{ states('sensor.duel_fuel_2_full_dose')|float / (states('input_number.peristaltic_pump_flow_rate')|float / 60 )}}"
      unit_of_measurement: "seconds"
    vitathrive_dose_length:
      friendly_name: "Vitathrive Dose Length"
      unique_id: vitathrive_dose_length
      value_template: "{{ states('sensor.vitathrive_full_dose')|float / (states('input_number.peristaltic_pump_flow_rate')|float / 60 )}}"
      unit_of_measurement: "seconds"
    rezin_dose_length:
      friendly_name: "Rezin Dose Length"
      unique_id: rezin_dose_length
      value_template: "{{ states('sensor.rezin_full_dose')|float / (states('input_number.peristaltic_pump_flow_rate')|float / 60 )}}"
      unit_of_measurement: "seconds"
    massive_bloom_dose_length:
      friendly_name: "Massive Bloom Dose Length"
      unique_id: massive_bloom_dose_length
      value_template: "{{ states('sensor.massive_bloom_full_dose')|float / (states('input_number.peristaltic_pump_flow_rate')|float / 60 )}}"
      unit_of_measurement: "seconds"
    liquid_weight_dose_length:
      friendly_name: "Liquid Weight Dose Length"
      unique_id: liquid_weight_dose_length
      value_template: "{{ states('sensor.liquid_weight_full_dose')|float / (states('input_number.peristaltic_pump_flow_rate')|float / 60 ) }}"
      unit_of_measurement: "seconds"
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /config
    - type: disk_use
    - type: disk_free
    - type: memory_use_percent
    - type: memory_use
    - type: memory_free
    - type: swap_use_percent
    - type: swap_use
    - type: swap_free
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: network_in
      arg: enp1s0
    - type: network_out
      arg: enp1s0
    - type: throughput_network_in
      arg: enp1s0
    - type: throughput_network_out
      arg: enp1s0
    - type: packets_in
      arg: enp1s0
    - type: packets_out
      arg: enp1s0
    - type: ipv4_address
      arg: enp1s0
    - type: ipv6_address
      arg: enp1s0
    - type: processor_use
    - type: processor_temperature
    - type: last_boot
