esphome:
  name: ph-sensor

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret ph-sensor-encryption-key

ota:
  password: !secret ph-sensor-ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ph-Sensor Fallback Hotspot"
    password: !secret ph-sensor-ap-password

captive_portal:

i2c:
  sda: GPIO23
  scl: GPIO22
  scan: true
  id: bus_a

sensor:
  - platform: ezo
    id: ph_ezo
    name: "ph"
    address: 99
    unit_of_measurement: "pH"
    update_interval: 60s
    accuracy_decimals: 2

button:
  - platform: template
    name: "cal 7"
    on_press:
      - lambda: id(ph_ezo).set_calibration_point_mid(7);
  - platform: template
    name: "cal 4"
    on_press:
      - lambda: id(ph_ezo).set_calibration_point_low(4.00);
  - platform: template
    name: "cal 10"
    on_press:
      - lambda: id(ph_ezo).set_calibration_point_high(10.00);
    
    