esphome:
  name: tds-sensor

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret tds-sensor-encryption-key

ota:
  password: !secret tds-sensor-ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tds-Sensor Fallback Hotspot"
    password: !secret tds-sensor-ap-password

captive_portal:
dallas:
  - pin: D5
# Raw TDS Reading
sensor:
  - platform: adc
    pin: A0
    name: "TDS 01 Voltage"
    id: tds01_raw
    update_interval: 60s
    unit_of_measurement: "v"
    accuracy_decimals: 3
    internal: true
    filters:
      - multiply: 3.3

  # Temperature In °C
  - platform: dallas
    address: 0xfb00000003f13528
    name: "Water Temperature"
    id: probe01
    accuracy_decimals: 1
    unit_of_measurement: "°C"

  # Temperature Compensated Voltage
  - platform: template
    name: "TDS 01 Temperature Adjusted Voltage"
    id: temp01_comp_v
    unit_of_measurement: "v"
    accuracy_decimals: 3
    lambda: "return ((id(tds01_raw).state) / (1 + (0.02 * ((id(probe01).state) - 25.0))));"
    update_interval: 60s
  #    internal: true

  # Temperature Compensated TDS
  - platform: template
    name: "TDS-01"
    id: tds01_55g
    icon: "hass:water-opacity"
    unit_of_measurement: "PPM"
    accuracy_decimals: 0
    lambda: return (133.42*(id(temp01_comp_v).state)*(id(temp01_comp_v).state)*(id(temp01_comp_v).state) - 255.86*(id(temp01_comp_v).state)*(id(temp01_comp_v).state) + 857.39*(id(temp01_comp_v).state))*0.5;

  - platform: wifi_signal
    name: "TDS-Sensor WiFi Signal Sensor"
    update_interval: 60s #to display WiFi signal strength

  - platform: homeassistant
    name: "Starting PPM from Home Assistant"
    id: startingppm
    entity_id: input_number.water_starting_ppm
  
  - platform: template
    name: "TDS Adjusted for Starting PPM"
    id: tds01_adj
    icon: "hass:water-opacity"
    unit_of_measurement: "PPM"
    accuracy_decimals: 0
    lambda: return id(tds01_55g)-id(startingppm);

