esphome:
  name: tent-environment

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret tent-environment-encryption-key

ota:
  password: !secret tent-environment-ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tent-Environment"
    password: !secret tent-environment-ap-password

captive_portal:
sensor:
  - platform: dht
    pin: D2
    temperature:
      name: "Tent Temperature"
    humidity:
      name: "Tent Humidity"
      filters:
        - calibrate_linear:
            - 0.0 -> 0.0
            - 66.0 -> 58.0
            - 86.0 -> 71.0
            - 100.0 -> 100.0
    model: AM2302
    update_interval: 60s

  - platform: wifi_signal
    name: "Tent-Environment WiFi Signal Sensor"
    update_interval: 60s #to display WiFi signal strength
